import color from 'color';

import { Platform, Dimensions, PixelRatio } from 'react-native';

const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;
const platform = Platform.OS;
const platformStyle = 'material';
const isIphoneX =
    platform === 'ios' && deviceHeight === 812 && deviceWidth === 375;

export default {
    'platformStyle': 'material',
    'platform': 'android',
    'androidRipple': true,
    'androidRippleColor': 'rgba(256, 256, 256, 0.3)',
    'androidRippleColorDark': 'rgba(0, 0, 0, 0.15)',
    'btnUppercaseAndroidText': true,
    'badgeBg': 'rgba(189,195,199,1)',
    'badgeColor': '#fff',
    'badgePadding': 3,
    'btnFontFamily': 'System',
    'btnDisabledBg': 'rgba(189,195,199,1)',
    'buttonPadding': 6,
    'btnPrimaryBg': 'rgba(52,73,94,1)',
    'btnPrimaryColor': '#fff',
    'btnInfoBg': '#3F57D3',
    'btnInfoColor': '#fff',
    'btnSuccessBg': 'rgba(5,196,107,1)',
    'btnSuccessColor': '#fff',
    'btnDangerBg': '#d9534f',
    'btnDangerColor': '#fff',
    'btnWarningBg': '#f0ad4e',
    'btnWarningColor': '#fff',
    'btnTextSize': 16.5,
    'btnTextSizeLarge': 22.5,
    'btnTextSizeSmall': 12,
    'borderRadiusLarge': 57,
    'iconSizeLarge': 45,
    'iconSizeSmall': 18,
    'cardDefaultBg': 'rgba(245,246,250,1)',
    'cardBorderColor': '#ccc',
    'CheckboxRadius': 0,
    'CheckboxBorderWidth': 2,
    'CheckboxPaddingLeft': 2,
    'CheckboxPaddingBottom': 0,
    'CheckboxIconSize': 18,
    'CheckboxFontSize': 21,
    'DefaultFontSize': 16,
    'checkboxBgColor': '#039BE5',
    'checkboxSize': 20,
    'checkboxTickColor': '#fff',
    'brandPrimary': 'rgba(44,44,84,1)',
    'brandInfo': '#3F57D3',
    'brandSuccess': '#5cb85c',
    'brandDanger': '#d9534f',
    'brandWarning': '#f0ad4e',
    'brandDark': '#000',
    'brandLight': 'rgba(236,240,241,1)',
    'fontFamily': 'System',
    'fontSizeBase': 15,
    'fontSizeH1': 28,
    'fontSizeH2': 22,
    'fontSizeH3': 18,
    'footerHeight': 55,
    'footerDefaultBg': 'rgba(52,73,94,1)',
    'footerPaddingBottom': 0,
    'tabBarTextColor': '#fff',
    'tabBarTextSize': 14,
    'activeTab': '#fff',
    'sTabBarActiveTextColor': 'rgba(72,84,96,1)',
    'tabBarActiveTextColor': 'rgba(236,240,241,1)',
    'tabActiveBgColor': 'rgba(44,62,80,1)',
    'toolbarBtnColor': '#fff',
    'toolbarDefaultBg': 'rgba(52,73,94,1)',
    'toolbarHeight': 64,
    'toolbarSearchIconSize': 20,
    'toolbarInputColor': '#fff',
    'searchBarHeight': 30,
    'searchBarInputHeight': 30,
    'toolbarBtnTextColor': '#fff',
    'toolbarDefaultBorder': 'rgba(189,195,199,1)',
    'iosStatusbar': 'light-content',
    'statusBarColor': 'rgba(52,73,94,1)',
    'darkenHeader': '#F0F0F0',
    'iconFamily': 'Ionicons',
    'iconFontSize': 30,
    'iconHeaderSize': 29,
    'inputFontSize': 17,
    'inputBorderColor': 'rgba(44,62,80,1)',
    'inputSuccessBorderColor': 'rgba(5,196,107,1)',
    'inputErrorBorderColor': 'rgba(231,76,60,1)',
    'inputHeightBase': 50,
    'inputColor': 'rgba(52,73,94,1)',
    'inputColorPlaceholder': 'rgba(52,73,94,1)',
    'btnLineHeight': 19,
    'lineHeightH1': 32,
    'lineHeightH2': 24,
    'lineHeightH3': 22,
    'lineHeight': 20,
    'listBg': 'rgba(255,255,255,1)',
    'listBorderColor': '#c9c9c9',
    'listDividerBg': '#f4f4f4',
    'listBtnUnderlayColor': '#DDD',
    'listItemPadding': 10,
    'listNoteColor': 'rgba(128,142,155,1)',
    'listNoteSize': 13,
    'defaultProgressColor': '#E4202D',
    'inverseProgressColor': '#1A191B',
    'radioBtnSize': 25,
    'radioSelectedColorAndroid': 'rgba(44,62,80,1)',
    'radioBtnLineHeight': 29,
    'segmentBackgroundColor': 'rgba(52,73,94,1)',
    'segmentActiveBackgroundColor': 'rgba(255,255,255,1)',
    'segmentTextColor': '#fff',
    'segmentActiveTextColor': 'rgba(44,62,80,1)',
    'segmentBorderColor': '#fff',
    'segmentBorderColorMain': '#3F51B5',
    'defaultSpinnerColor': 'rgba(44,62,80,1)',
    'inverseSpinnerColor': '#1A191B',
    'tabDefaultBg': '#3F51B5',
    'topTabBarTextColor': '#b3c7f9',
    'topTabBarActiveTextColor': '#fff',
    'topTabBarBorderColor': '#fff',
    'topTabBarActiveBorderColor': '#fff',
    'tabBgColor': '#F8F8F8',
    'tabFontSize': 15,
    'textColor': 'rgba(72,84,96,1)',
    'inverseTextColor': '#fff',
    'noteFontSize': 14,
    'defaultTextColor': '#000',
    'titleFontfamily': 'System',
    'titleFontSize': 19,
    'subTitleFontSize': 14,
    'subtitleColor': 'rgba(236,240,241,1)',
    'titleFontColor': '#FFF',
    'borderRadiusBase': 2,
    'borderWidth': 1,
    'contentPadding': 10,
    'dropdownLinkColor': 'rgba(52,73,94,1)',
    'inputLineHeight': 24,
    'deviceWidth': 1517,
    'deviceHeight': 730,
    'isIphoneX': false,
    'inputGroupRoundedBorderRadius': 30
}
