export const agentActionsConstants = {
  START_SHIFT_ATTENDANCE:'START_SHIFT_ATTENDANCE',
  END_SHIFT: 'END_SHIFT',
  START_BREAK: 'START_BREAK',
  END_BREAK: 'END_BREAK',
  GET_AGENT_STATUS: 'GET_AGENT_STATUS',
  UPDATE_AGENT_LAST_ACTION: 'UPDATE_AGENT_LAST_ACTION'
};
